### ISSUE TITLE
Incorrect result when querying against date field

### ISSUE THREAD

**Issue by rerosum** [objectbox/objectbox-go#19]
Please see attached sample project with failing test case.
[testObjectBox.zip](https://github.com/objectbox/objectbox-go/files/4032566/testObjectBox.zip)

**Comment by vaind** [comment]
Go's `time.Time` struct is a complex type and requires a "converter" to store in the database. This converter is (as of ObjectBox Go 1.1) assigned automatically and used when storing and retrieving the data. 

However, the query expects the already converted value (see `func (property PropertyInt64) GreaterThan(value int64) Condition`). There are no methods generated for the custom/complex type when using converters - the query methods expect the actual stored type & data.

Therefore, the usage in the failing test should look like this instead:
```go
func TestGreaterThanDate(t *testing.T) {
	storedTime, err := objectbox.TimeInt64ConvertToDatabaseValue(t2)
	if err != nil {
		t.Error(err)
	}
	q := personBox.Query(
		person.Person_.Time.GreaterThan(storedTime),
		person.Person_.Time.OrderAsc(),
	)
	people, _ := q.Find()
	if people[0].Time.Unix() != t1.Unix() {
		t.Errorf("Expected t1 (%d) but got %d\nt0: %d, t1: %d, t2: %d", t1.Unix(), people[0].Time.Unix(), t0.Unix(), t1.Unix(), t2.Unix())
	}
}
```
With `TimeInt64ConvertToDatabaseValue` being one of the few built in converters you can use instead of defining a custom one.

Thanks for pointing this out. We will update the docs to mention this and also create an internal issue to track whether there can be something helpful done using code generation.

**Comment by vaind** [comment]
Updated docs: https://golang.objectbox.io/custom-types#queries

**Comment by rerosum** [comment]
Thanks for the clarification.
