### ISSUE TITLE
Encryption & static linking

### ISSUE THREAD

**Issue by MagnifiGo** [objectbox/objectbox-go#31]
Hello,

I really like ObjectBox, and I would love to add it to my stack and build software around it, however  the lack of encryption support in the Go incarnation makes it a no go (pun intended). Are there any plans to add encryption to the Go incarnation of ObjectBox?

Also, I need to static link the lib, however no static build is being offered currently. What do I need to do to achieve this?

**Comment by vaind** [comment]
You've correctly found out that neither is currently available, but not limited to Go. 

There're existing requests for "encryption" in [objectbox-java](https://github.com/objectbox/objectbox-java/issues/8) and [objectbox-dart](https://github.com/objectbox/objectbox-dart/issues/221), probably no need to create yet another one since they all depend on the availability of encryption in the ObjectBox core library.

As for a static library, I don't think this is something planned to be generally available. You can, however, reach out with a request via https://objectbox.io/contact/

**Comment by MagnifiGo** [comment]
@vaind , thank you for the clarifications.
